"""Terminal manual for the pipeline.

`man usage` is a hand-written overview; `man config` is generated by walking
the Pydantic models, so the config reference can never drift from the schema.
"""
import textwrap
import types
import typing

from pydantic import BaseModel
from pydantic_core import PydanticUndefined

from .config.schema import CollectConfig

USAGE = """\
carla_data_pipeline - config-driven headless CARLA data collection

STAGES
  1. collect        needs a running CARLA server; writes the per-frame groups
                    (/images, /telemetry, /map_context, /camera_config) of
                    data/runs/<run_id>.h5 plus a <run_id>.json sidecar
  2. build-samples  offline; appends the per-sample groups (/sample_index,
                    /trajectory, /action) into the same .h5
  3. upload         ships <run_id>.h5 + .json to the configured private HF
                    dataset repo, verifies size, then (per config) deletes the
                    local .h5; runs automatically after build-samples when
                    upload.enabled + upload.auto

COMMANDS
  collect <scenario.yaml> [--run-id ID] [--dry-run | --verify-only]
      --dry-run      validate + print the resolved config; never touches CARLA
      --verify-only  connect and check map/spawn/blueprints, spawn nothing
  build-samples <run_id | path.h5> [--no-upload]
  upload <run_id | path.h5> | --all
      idempotent; --all backfills every built run in --data-dir
  export-video <run_id | path.h5> [--camera CAM]... [--out-dir DIR] [--crf N]
      viewing tool: rebuild one h264 mp4 per camera from the raw frames
      into data/videos/<run_id>/; needs ffmpeg, touches nothing in the run
  man [usage | config]

TYPICAL SESSION
  $ hf auth login    # once; upload destination is configs/base.yaml upload.repo_id
  $ ~/CARLA_0.9.16/CarlaUE4.sh -RenderOffScreen -nosound &   # never -quality-level=Low (carla#4940)
  $ python -m carla_data_pipeline collect configs/scenarios/town10_light_traffic.yaml
  $ python -m carla_data_pipeline build-samples run01        # auto-uploads + prunes local .h5

CONFIG FILES
  configs/base.yaml           shared defaults (connection, capture params)
  configs/camera_spec/*.yaml  camera rigs, referenced via `camera_spec:`
  configs/scenarios/*.yaml    what you pass to collect; `extends: ../base.yaml`

  A scenario deep-merges over base (scenario wins). Run identity (runNN) is
  assigned at collect time, never written in configs. Full field reference:
  `man config`.

DATA LAYOUT
  data/runs/<run_id>.h5    self-contained run (schema: data/README.md)
  data/runs/<run_id>.json  human/LLM-readable sidecar: resolved config, seed,
                           counts, stage status
"""


def _unwrap_optional(annotation):
    """Return (inner_annotation, is_optional)."""
    if typing.get_origin(annotation) in (typing.Union, types.UnionType):
        args = [a for a in typing.get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return args[0], True
    return annotation, False


def _nested_model(annotation):
    """The BaseModel subclass inside annotation (direct, Optional or list), if any."""
    annotation, _ = _unwrap_optional(annotation)
    if typing.get_origin(annotation) is list:
        annotation = typing.get_args(annotation)[0]
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation
    return None


def _type_name(annotation):
    annotation, optional = _unwrap_optional(annotation)
    suffix = " | none" if optional else ""
    if typing.get_origin(annotation) is typing.Literal:
        return " | ".join(repr(a) for a in typing.get_args(annotation)) + suffix
    if typing.get_origin(annotation) is list:
        return f"list of {_type_name(typing.get_args(annotation)[0])}" + suffix
    if isinstance(annotation, type):
        return annotation.__name__ + suffix
    return str(annotation) + suffix


def render_config(model: type[BaseModel] = CollectConfig, indent: int = 0) -> str:
    lines = []
    if indent == 0:
        lines.append("Scenario config reference (generated from the Pydantic schema).")
        lines.append("Sections nest as shown; unknown keys are rejected everywhere.")
        lines.append("")
    pad = "  " * indent
    for name, field in model.model_fields.items():
        nested = _nested_model(field.annotation)
        if field.is_required():
            tail = "(required)"
        elif nested or field.default is PydanticUndefined or field.default is None:
            tail = ""
        else:
            tail = f"= {field.default!r}"
        head = f"{pad}{name}: {_type_name(field.annotation)} {tail}".rstrip()
        lines.append(head)
        if field.description:
            lines.extend(textwrap.wrap(field.description, width=76,
                                       initial_indent=pad + "    ",
                                       subsequent_indent=pad + "    "))
        if nested:
            lines.append(render_config(nested, indent + 1))
    return "\n".join(lines)


def render(topic: str) -> str:
    return USAGE if topic == "usage" else render_config()
